package org.daumantas.myBatis.DAO;

import java.util.List;
import org.daumantas.myBatis.model.KingMission;
import org.mybatis.cdi.Mapper;

@Mapper
public interface KingMissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KING_MISSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    int insert(KingMission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KING_MISSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    List<KingMission> selectAll();
}