package org.daumantas.myBatis.DAO;

import java.util.List;
import org.daumantas.myBatis.model.Knight;
import org.mybatis.cdi.Mapper;

@Mapper
public interface KnightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KNIGHT
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KNIGHT
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    int insert(Knight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KNIGHT
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    Knight selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KNIGHT
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    List<Knight> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.KNIGHT
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    int updateByPrimaryKey(Knight record);

    List<Knight> selectByKingId(Long id);
}