package org.daumantas.myBatis.DAO;

import java.util.List;
import org.daumantas.myBatis.model.Mission;
import org.mybatis.cdi.Mapper;

@Mapper
public interface MissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    int insert(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    Mission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    List<Mission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    int updateByPrimaryKey(Mission record);

    List<Mission> selectByKingId(Long id);
    Mission selectLast();
}