package org.daumantas.myBatis.model;

public class KingMission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KING_MISSION.KINGS_ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    private Long kingsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KING_MISSION.MISSIONS_ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    private Long missionsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KING_MISSION.KINGS_ID
     *
     * @return the value of PUBLIC.KING_MISSION.KINGS_ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public Long getKingsId() {
        return kingsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KING_MISSION.KINGS_ID
     *
     * @param kingsId the value for PUBLIC.KING_MISSION.KINGS_ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public void setKingsId(Long kingsId) {
        this.kingsId = kingsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KING_MISSION.MISSIONS_ID
     *
     * @return the value of PUBLIC.KING_MISSION.MISSIONS_ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public Long getMissionsId() {
        return missionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KING_MISSION.MISSIONS_ID
     *
     * @param missionsId the value for PUBLIC.KING_MISSION.MISSIONS_ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public void setMissionsId(Long missionsId) {
        this.missionsId = missionsId;
    }
}