package org.daumantas.myBatis.model;

public class Knight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KNIGHT.ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KNIGHT.NAME
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KNIGHT.PROFESSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.KNIGHT.KING_ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    private Long kingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KNIGHT.ID
     *
     * @return the value of PUBLIC.KNIGHT.ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KNIGHT.ID
     *
     * @param id the value for PUBLIC.KNIGHT.ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KNIGHT.NAME
     *
     * @return the value of PUBLIC.KNIGHT.NAME
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KNIGHT.NAME
     *
     * @param name the value for PUBLIC.KNIGHT.NAME
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KNIGHT.PROFESSION
     *
     * @return the value of PUBLIC.KNIGHT.PROFESSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KNIGHT.PROFESSION
     *
     * @param profession the value for PUBLIC.KNIGHT.PROFESSION
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public void setProfession(String profession) {
        this.profession = profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.KNIGHT.KING_ID
     *
     * @return the value of PUBLIC.KNIGHT.KING_ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public Long getKingId() {
        return kingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.KNIGHT.KING_ID
     *
     * @param kingId the value for PUBLIC.KNIGHT.KING_ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public void setKingId(Long kingId) {
        this.kingId = kingId;
    }
}