package org.daumantas.myBatis.model;

public class Mission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MISSION.ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MISSION.COUNTRY
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MISSION.TITLE
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MISSION.ID
     *
     * @return the value of PUBLIC.MISSION.ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MISSION.ID
     *
     * @param id the value for PUBLIC.MISSION.ID
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MISSION.COUNTRY
     *
     * @return the value of PUBLIC.MISSION.COUNTRY
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MISSION.COUNTRY
     *
     * @param country the value for PUBLIC.MISSION.COUNTRY
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MISSION.TITLE
     *
     * @return the value of PUBLIC.MISSION.TITLE
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MISSION.TITLE
     *
     * @param title the value for PUBLIC.MISSION.TITLE
     *
     * @mbg.generated Thu Apr 01 11:11:56 EEST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }
}